apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-fetch
---
apiVersion: v1
kind: Service
metadata:
  name: client-fetch
  labels:
    app: client-fetch
    service: client-fetch
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 80
  selector:
    app: client-fetch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-fetch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-fetch
      version: v1
  template:
    metadata:
      labels:
        app: client-fetch
        version: v1
    spec:
      serviceAccountName: client-fetch
      containers:
      - image: wmangerva/nginx-fetch-gloo
        imagePullPolicy: Always
        name: client-fetch
        ports:
        - containerPort: 80
