apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin-api
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-api
  labels:
    app: httpbin-api
    service: httpbin-api
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-api
      version: v1
  template:
    metadata:
      labels:
        app: httpbin-api
        version: v1
    spec:
      serviceAccountName: httpbin-api
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin-api
        ports:
        - containerPort: 80
