apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin-ui
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-ui
  labels:
    app: httpbin-ui
    service: httpbin-ui
spec:
  ports:
  - name: http
    port: 8081
    targetPort: 80
  selector:
    app: httpbin-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-ui
      version: v1
  template:
    metadata:
      labels:
        app: httpbin-ui
        version: v1
    spec:
      serviceAccountName: httpbin-ui
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin-ui
        ports:
        - containerPort: 80
