apiVersion: v1
items:
- apiVersion: gloo.solo.io/v1
  kind: Settings
  metadata:
    annotations:
      meta.helm.sh/release-name: gloo
      meta.helm.sh/release-namespace: gloo-system
    creationTimestamp: "2022-03-28T20:54:15Z"
    generation: 1
    labels:
      app: gloo
      app.kubernetes.io/managed-by: Helm
      gloo: settings
    name: default
    namespace: gloo-system
    resourceVersion: "3239"
    uid: bf78a3e3-7227-4951-822a-6273db9488af
  spec:
    discovery:
      fdsMode: WHITELIST
    discoveryNamespace: gloo-system
    extauth:
      requestTimeout: 1s
      extauthzServerRef:
        name: extauth
        namespace: gloo-system
      transportApiVersion: V3
      userIdHeader: x-user-id
    gateway:
      readGatewaysFromAllNamespaces: false
      validation:
        allowWarnings: true
        alwaysAccept: true
        disableTransformationValidation: false
        proxyValidationServerAddr: gloo:9988
        validationServerGrpcMaxSizeBytes: 4000000
        warnRouteShortCircuiting: false
    gloo:
      disableKubernetesDestinations: false
      disableProxyGarbageCollection: false
      enableRestEds: false
      invalidConfigPolicy:
        invalidRouteResponseBody: Gloo Gateway has invalid configuration. Administrators
          should run `glooctl check` to find and fix config errors.
        invalidRouteResponseCode: 404
        replaceInvalidRoutes: false
      restXdsBindAddr: 0.0.0.0:9976
      xdsBindAddr: 0.0.0.0:9977
    kubernetesArtifactSource: {}
    kubernetesConfigSource: {}
    kubernetesSecretSource: {}
    ratelimitServer:
      rateLimitBeforeAuth: false
      ratelimitServerRef:
        name: rate-limit
        namespace: gloo-system
    refreshRate: 60s
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
